services:
  relay:
    container_name: relay
    image: msalia/shayona-relay:latest
    env_file: ".env"
    ports:
      - ${PORT}:${PORT}
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      METRICS_PORT: ${METRICS_PORT}
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASS}@db/${DATABASE}
      RUST_LOG: ${RUST_LOG}
    networks:
      - relay-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4.0-oraclelinux8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
      MYSQL_TCP_BIND_ADDRESS: ${MYSQL_BIND_ADDRESS}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 3s
      timeout: 5s
      retries: 3
    networks:
      - relay-network

volumes:
  mysql-data:

networks:
  relay-network: